---
  - name: MAGENTO 2.3 COMMUNITY - check if Magento already exists
    stat:
      path: '{{magento_docroot}}/index.php'
    register: magento_index_result

  - name: MAGENTO 2.3 COMMUNITY - create project and install
    block:
      - name: MAGENTO 2.3 COMMUNITY - set repository global config using Composer
        command: composer global config http-basic.repo.magento.com "{{ magento_public_key }}" "{{ magento_private_key }}"
        no_log: true

      - name: MAGENTO 2.3 COMMUNITY - create Magento 2.3 project via Composer
        command: /usr/local/bin/composer create-project --repository=https://repo.magento.com/ magento/project-community-edition {{ magento_docroot }}

      - name: MAGENTO 2.3 COMMUNITY - copy reinstall script /var/www/html/reinstall.sh
        template:
          src: var/www/html/reinstall.sh.j2
          dest: /var/www/html/reinstall.sh
          owner: '{{magento_www_user}}'
          group: '{{magento_www_group}}'
          mode: 0664

      - name: MAGENTO 2.3 COMMUNITY - make bin/magento executable
        command: 'chmod u+x {{magento_docroot}}/bin/magento'
    when: magento_index_result.stat.exists == false

#  - yum:
#      name: http://widehat.opensuse.org/opensuse/distribution/leap/42.3/repo/oss/suse/noarch/python-pexpect-3.3-6.1.noarch.rpm
#      state: present
#  - yum:
#      name: python-pexpect
#      state: present
